news_sites:
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.field-content a'
  forbes:
    url: https://forbes.co
    queries:
      homepage_article_links: '.channel__content a'